<?php 
$config['id'] = '1'; 
$config['site_contact_mail'] = 'info@gainturnkeyproperty.com';
$config['site_contact_number'] = '877-372-2010'; 
$config['email_title'] = 'Gain Turkey Admin';
$config['google_verification'] = '<meta name=\'google-site-verification\' content=\'uvDBJtHtyZfvfv_a0LuyJeXOMTZqGzi4bXTSGfKodGc\' />'; 
$config['google_verification_code'] = '<script type=\"text/javascript\">
  var _gaq = _gaq || [];
  _gaq.push([\'_setAccount\', \'UA-20025738-1\']);
  _gaq.push([\'_trackPageview\']);
  (function() {
    var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;
    ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';
    var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>'; 
$config['facebook_link'] = ''; 
$config['twitter_link'] = ''; 
$config['pinterest'] = ''; 
$config['googleplus_link'] = 'http://google.com'; 
$config['linkedin_link'] = 'https://www.instagram.com/mdgalleries/'; 
$config['rss_link'] = ''; 
$config['youtube_link'] = ''; 
$config['footer_content'] = ''; 
$config['logo_image'] = 'logo.png'; 
$config['meta_title'] = 'Gain Turkey';
$config['meta_keyword'] = 'turnkey, rentals, income property, real estate solutions, home, design, people helping people '; 
$config['meta_description'] = 'Real Estate Solutions | Turn Key Real Estate | Home | Design | People Helping People'; 
$config['fevicon_image'] = 'logo1.png'; 
$config['facebook_api'] = ''; 
$config['facebook_secret_key'] = ''; 
$config['paypal_api_name'] = ''; 
$config['paypal_api_pw'] = ''; 
$config['paypal_api_key'] = ''; 
$config['authorize_net_key'] = ''; 
$config['paypal_id'] = 'gopinath@teamtweaks.com'; 
$config['paypal_live'] = '2'; 
$config['smtp_port'] = '587';
$config['smtp_uname'] = 'sprajapati@innovegicsolutions.in';
$config['smtp_password'] = 'InvSp@11718';
$config['consumer_key'] = ''; 
$config['consumer_secret'] = ''; 
$config['google_client_secret'] = ''; 
$config['google_client_id'] = ''; 
$config['google_redirect_url'] = ''; 
$config['google_developer_key'] = ''; 
$config['facebook_app_id'] = ''; 
$config['facebook_app_secret'] = ''; 
$config['like_text'] = 'Like'; 
$config['unlike_text'] = 'Unlike'; 
$config['liked_text'] = 'Like\'d'; 
$config['instagram_url'] = ''; 
$config['booking_code'] = '1234'; 
$config['map_option'] = '1'; 
$config['created'] = '2013-07-17'; 
$config['modified'] = '2018-07-23'; 
$config['admin_name'] = 'GainTurkeyAdmin';
$config['email'] = 'info@gainturnkeyproperty.com';
$config['admin_type'] = 'super'; 
$config['privileges'] = 'a:10:{s:5:\"users\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:8:\"category\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:11:\"subcategory\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:7:\"product\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:6:\"slider\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:5:\"video\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:3:\"cms\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:5:\"order\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:10:\"statistics\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}s:10:\"newsletter\";a:4:{i:0;s:1:\"0\";i:1;s:1:\"1\";i:2;s:1:\"2\";i:3;s:1:\"3\";}}'; 
$config['crm_privileges'] = ''; 
$config['last_login_date'] = '2018-07-23 01:40:20'; 
$config['last_logout_date'] = '2018-07-20 01:18:28'; 
$config['last_login_ip'] = '107.191.0.113'; 
$config['is_verified'] = 'Yes'; 
$config['status'] = 'Active'; 
// $config['base_url'] = 'http://www.returnonrentals.com/';  
$config['base_url'] = 'http://localhost/gainturkey/';
?>
