<?php 
$config['currency_id'] = '215'; 
$config['currency_contid'] = 'AF'; 
$config['currency_country_code'] = 'US'; 
$config['currency_name'] = 'United States of America'; 
$config['currency_seourl'] = 'united-states-of-america'; 
$config['currency_currency_type'] = 'USD'; 
$config['currency_currency_symbol'] = '$'; 
$config['currency_shipping_cost'] = '0.00'; 
$config['currency_shipping_tax'] = '0.00'; 
$config['currency_meta_title'] = ''; 
$config['currency_meta_keyword'] = ''; 
$config['currency_meta_description'] = ''; 
$config['currency_description'] = '<p>rrr</p>';
$config['currency_status'] = 'Active';
$config['currency_dateAdded'] = '2019-04-06 05:29:18'; 
$config['currency_currency_default'] = 'Yes';
$config['currency_slider_image'] = '0';
$config['currency_logo'] = '800px-Flag_of_the_United_States.svg_.png';
$config['currency_map'] = '0';
$config['currency_thumb'] = '800px-Flag_of_the_United_States.svg_1.png'; ?>
